### ISSUE TITLE
Problem starting with 'routes'

### ISSUE THREAD

**Issue by ph10vis** [cracksuxer/chimp#3]
```sh
Uncaught ReferenceError: Cannot access 'routes' before initialization
    at Module.routes (useGame.tsx:88:1)
    at ./src/routes/Games.tsx (Games.tsx:7:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/index.tsx (useGame.tsx:88:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:7:1
    at startup:7:1
```

> Current branch: master

When I try to launch the game, this error appears

**Comment by ph10vis** [comment]
Fixed by @rutuser
